### ISSUE TITLE
dependency constraints

### ISSUE THREAD

**Issue by fabiocarneiro** [zendframework/zend-expressive-zendviewrenderer#17]
Its possible to install this with expressive 0.x, but it requires `zendframework/zend-expressive-helpers` 1.1, which uses `attachRouteResultObserver` which is available only on master.

**Comment by weierophinney** [comment]
This is a temporary situation, as a stable version of zend-expressive has not yet been released. I'm preparing RC3 currently, which should resolve the situation.

**Comment by fabiocarneiro** [comment]
@weierophinney But even with the rc tag, if you don't add a dependency constraint to 1.x to zendviewrenderer or any of the modules in the dependency tree it will still allow us to install expressive 0.x.

https://github.com/zendframework/zend-expressive-zendviewrenderer/blob/1.0.0/composer.json#L24
As you see it depends on helpers 1.1 and this one doesn't depend on any version of expressive but on router 1.1. And router 1.1 also doesn't depend on expressive.
https://github.com/zendframework/zend-expressive-helpers/blob/master/composer.json#L19-L22 and
https://github.com/zendframework/zend-expressive-router/blob/master/composer.json#L20-L21

If I didn't miss something, you can even install zendviewrenderer, helpers and router without expressive.

**Comment by weierophinney** [comment]
@fabiocarneiro Yes, you can install this package, the helpers, and the router without Expressive.

The real question is: what real-world scenario do you envision where somebody would install them alongside Expressive `<1.0.0rc3`? This feels like a case of "what if?" versus a real concern.
