### ISSUE TITLE
NamespacedPathStackResolver - adding default suffix to template

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-expressive-zendviewrenderer#28]
After a while of digging I find that [NamespacedPathStackResolver](https://github.com/zendframework/zend-expressive-zendviewrenderer/blob/master/src/NamespacedPathStackResolver.php#L172) do not add default suffix if I try to render eg: `$template->render('mail::body.html', []);` which should be imho resolved to `body.html.phtml`.

Is this bug or expected behavior?

**Comment by geerteltink** [comment]
You highlight the answer yourself. 

``` php
        if (pathinfo($template, PATHINFO_EXTENSION) == '') {
            $template .= '.' . $defaultSuffix;
        }
```

What it does is it checks if there is already an extension. If there is none it appends `$defaultSuffix`. So in your example it detects `.html` as an extension and will not add `.phtml`.
