### ISSUE TITLE
Does the README need an update?

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-expressive-zendviewrenderer#29]
Today we stumbled upon the fact that the README claims you'd need to add the factory for the UrlHelper while it already get's added manually [in here](https://github.com/zendframework/zend-expressive-zendviewrenderer/blob/ca34ef052cefb48de5de6c519e61bbaf7870ea97/src/ZendViewRendererFactory.php#L107). 
Since the mentioned UrlHelperFactory has been removed in PR #13 i guess this part can be removed?

**Comment by weierophinney** [comment]
The README no longer references the `UrlHelper`; closing.
